// Generated by jextract

package org.libjpegturbo.turbojpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int num;
 *     int denom;
 * }
 * }
 */
public class tjscalingfactor {

    tjscalingfactor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        turbojpeg_h.C_INT.withName("num"),
        turbojpeg_h.C_INT.withName("denom")
    ).withName("$anon$951:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt num$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int num
     * }
     */
    public static final OfInt num$layout() {
        return num$LAYOUT;
    }

    private static final long num$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int num
     * }
     */
    public static final long num$offset() {
        return num$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int num
     * }
     */
    public static int num(MemorySegment struct) {
        return struct.get(num$LAYOUT, num$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int num
     * }
     */
    public static void num(MemorySegment struct, int fieldValue) {
        struct.set(num$LAYOUT, num$OFFSET, fieldValue);
    }

    private static final OfInt denom$LAYOUT = (OfInt)$LAYOUT.select(groupElement("denom"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int denom
     * }
     */
    public static final OfInt denom$layout() {
        return denom$LAYOUT;
    }

    private static final long denom$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int denom
     * }
     */
    public static final long denom$offset() {
        return denom$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int denom
     * }
     */
    public static int denom(MemorySegment struct) {
        return struct.get(denom$LAYOUT, denom$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int denom
     * }
     */
    public static void denom(MemorySegment struct, int fieldValue) {
        struct.set(denom$LAYOUT, denom$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

